FROM python:3.8.9
WORKDIR /

COPY requirements.txt app.py  .flaskenv backend/ ./
RUN pip install -r ./requirements.txt
RUN pip install gunicorn 
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:app"]