"""empty message

Revision ID: 1270460b38bc
Revises: 256daa4662f1
Create Date: 2022-01-23 15:16:42.722319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1270460b38bc'
down_revision = '256daa4662f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=40), nullable=True),
    sa.Column('profileImage', sa.String(), nullable=True),
    sa.Column('photoUrl', sa.String(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
