"""empty message

Revision ID: 6ec21830c3bf
Revises: 1270460b38bc
Create Date: 2022-01-23 15:25:23.941040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ec21830c3bf'
down_revision = '1270460b38bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('userslikes', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'userslikes')
    # ### end Alembic commands ###
